### ISSUE TITLE
Unable to authenticate with pre-authenticated browser?

### ISSUE THREAD

**Issue by ngcubed** [msaxon/recipe-book#18]
I'm getting this error when coming to msaxon.github.io/recipe-book being already signed into chrome:

`cb=gapi.loaded_0:360 Uncaught fw message: "gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init()."stack: "gapi.auth2.ExternallyVisibleError: gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init().↵    at new fw (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.76xGL2Yny_o.O/m=signin2/rt=j/sv=1/d=1/ed=1/am=wQE/rs=AGLTcCPLubAJPE__-DfP0tDIR1-cduAt3Q/cb=gapi.loaded_0:323:25)↵    at Object._.nx [as init] (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.76xGL2Yny_o.O/m=signin2/rt=j/sv=1/d=1/ed=1/am=wQE/rs=AGLTcCPLubAJPE__-DfP0tDIR1-cduAt3Q/cb=gapi.loaded_0:360:126)↵    at https://msaxon.github.io/recipe-book/static/js/main.29d8dd2c.chunk.js:1:57511↵    at https://msaxon.github.io/recipe-book/static/js/2.7d57bf4c.chunk.js:2:87547↵    at jb (https://msaxon.github.io/recipe-book/static/js/2.7d57bf4c.chunk.js:2:82513)↵    at t (https://msaxon.github.io/recipe-book/static/js/2.7d57bf4c.chunk.js:2:87529)↵    at Array.Qb.b.<computed> (https://msaxon.github.io/recipe-book/static/js/2.7d57bf4c.chunk.js:2:87627)↵    at Object.Qb.I.<computed> [as loaded_1] (https://msaxon.github.io/recipe-book/static/js/2.7d57bf4c.chunk.js:2:87686)↵    at https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.76xGL2Yny_o.O/m=auth2,client/exm=signin2/rt=j/sv=1/d=1/ed=1/am=wQE/rs=AGLTcCPLubAJPE__-DfP0tDIR1-cduAt3Q/cb=gapi.loaded_1:1:15"__proto__: _.adconstructor: ƒ (a)name: "gapi.auth2.ExternallyVisibleError"__proto__: Error`

**Comment by msaxon** [comment]
looks  like this happens when i try and make the auth show up in the same page instead of a new window. right now, its windowed so it should be fine. Lemme know if its not.

**Comment by ngcubed** [comment]
just tried again and had no issue. closing this issue.
